### ISSUE TITLE
revisit the pre-commit configuration 

### ISSUE THREAD

**Issue by 12rambau** [Alexis-benoist/eralchemy#106]
Align the pre-commit configuration on more modern packages. 

I have my little favorites that cover most of the uses: 

```yaml
repos:
  - repo: "https://github.com/psf/black"
    rev: "22.3.0"
    hooks:
      - id: black
        stages: [commit]

  - repo: "https://github.com/pre-commit/mirrors-prettier"
    rev: "v2.7.1"
    hooks:
      - id: prettier
        stages: [commit]
        exclude: tests\/test_.+\.

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.215"
    hooks:
      - id: ruff
        stages: [commit]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        stages: [commit]
        additional_dependencies:
          - tomli
  ```
